version: '3.8'
services:
  spring-app:
    build: .
    container_name: spring_app
    ports:
      - "8080:8080"  # Маппинг порта контейнера на хост
    depends_on:
      - postgres  # Зависящий сервис (PostgreSQL)
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root

  postgres:
    image: postgres:14
    container_name: postgres_db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
